<a href="https://colab.research.google.com/github/30Umamaheswari/HouseRent/blob/main/HouseRent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
house_train = pd.read_excel('House_Rent_Train.xlsx')
house_train.head(2)

,id,type,locality,activation_date,latitude,longitude,lease_type,gym,lift,swimming_pool,...,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies,rent
0,ff8081815733a243015733b2876600a6,BHK2,NaN,21-04-2018 14:44,12.934471,77.634471,FAMILY,1,1,1,...,2.0,E,2.0,6.0,12.0,"{""LIFT"":true,""GYM"":true,""INTERNET"":true,""AC"":f...",CORP_BORE,AP,2.0,40000.0
1,ff8081815ee25e15015ee50004da2acd,BHK2,Bellandur,2017-09-10 12:48:00,12.929557,77.672280,ANYONE,0,1,0,...,2.0,NE,2.0,3.0,4.0,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORPORATION,AP,2.0,22000.0

In [3]:
house_train.shape

(20555, 25)

In [4]:
house_train = house_train.dropna(subset=['rent','amenities'])

In [ ]:
import json

# Extract amenities information
amenities_list = house_train['amenities']

# Initialize a dictionary to store extracted values
amenities_dict = {}

# Iterate through each row
for am in amenities_list:
    amen_dict = json.loads(am)

    # Ensure that all keys are present in each row
    for key in amen_dict.keys():
        if key not in amenities_dict:
            amenities_dict[key] = []

    # Append values to the dictionary, filling with None if key is missing
    for key in amenities_dict.keys():
        amenities_dict[key].append(amen_dict.get(key, False))

# Add new columns for each amenity to the existing DataFrame
for key, values in amenities_dict.items():
    house_train[key] = values

# Display the modified DataFram
house_train

In [6]:
house_train = house_train.dropna(subset=['type','locality'])

In [ ]:
house_train.isna().sum()

In [ ]:
house_train.shape

In [ ]:
house_train['GYM'] = house_train['GYM'].astype(int)
house_train['LIFT'] = house_train['LIFT'].astype(int)
house_train['INTERNET'] = house_train['INTERNET'].astype(int)
house_train['AC'] = house_train['AC'].astype(int)
house_train['CLUB'] = house_train['CLUB'].astype(int)
house_train['INTERCOM'] = house_train['INTERCOM'].astype(int)
house_train['POOL'] = house_train['POOL'].astype(int)
house_train['CPA'] = house_train['CPA'].astype(int)
house_train['FS'] = house_train['FS'].astype(int)
house_train['SERVANT'] = house_train['SERVANT'].astype(int)
house_train['SECURITY'] = house_train['SECURITY'].astype(int)
house_train['SC'] = house_train['SC'].astype(int)
house_train['GP'] = house_train['GP'].astype(int)
house_train['PARK'] = house_train['PARK'].astype(int)
house_train['RWH'] = house_train['RWH'].astype(int)
house_train['STP'] = house_train['STP'].astype(int)
house_train['HK'] = house_train['HK'].astype(int)
house_train['PB'] = house_train['PB'].astype(int)
house_train['VP'] = house_train['VP'].astype(int)

In [ ]:
house_train['bathroom'] = house_train['bathroom'].astype(int)
house_train['cup_board'] = house_train['cup_board'].astype(int)
house_train['floor'] = house_train['floor'].astype(int)
house_train['total_floor'] = house_train['total_floor'].astype(int)

In [ ]:
house_train['property_size'] = house_train['property_size'].astype(int)
house_train['property_age'] = house_train['property_age'].astype(int)
house_train['balconies'] = house_train['balconies'].astype(int)
house_train['rent'] = house_train['rent'].astype(int)
house_train['negotiable'] = house_train['negotiable'].astype(int)

house_train['latitude'] = house_train['latitude'].astype(float)
house_train['longitude'] = house_train['longitude'].astype(float)

house_train['locality'] = house_train['locality'].astype(str)
house_train['type'] = house_train['type'].astype(str)
house_train['id'] = house_train['id'].astype(str)
house_train['lease_type'] = house_train['lease_type'].astype(str)
house_train['furnishing'] = house_train['furnishing'].astype(str)
house_train['parking'] = house_train['parking'].astype(str)
house_train['facing'] = house_train['facing'].astype(str)
house_train['water_supply'] = house_train['water_supply'].astype(str)
house_train['building_type'] = house_train['building_type'].astype(str)

In [12]:
remove_columns = ['gym', 'lift', 'swimming_pool','amenities']
house_train = house_train.drop(columns = remove_columns)

In [13]:
house_train = house_train.rename(columns={'id':'ID','type':'House Type','locality':'Locality','activation_date':'Activation Date','latitude':'Latitude','longitude':'Longitude',
                            'lease_type':'Lease Type','furnishing':'Furnishing','parking':'Parking','property_size':'Property Size','property_age':'Property Age',
                            'bathroom':'No of Bathroom','facing':'House Facing','cup_board':'No of Cup Board','floor':'Floor No Floor','water_supply':'Water Supply',
                            'building_type':'Building Type','balconies':'Balconies','rent':'Rent','negotiable':'Negotiable','LIFT':'Lift', 'GYM':'Gym', 'INTERNET':'Internet',
                            'AC':'Air Conditioning','CLUB':'Club', 'INTERCOM':'Intercom', 'POOL':'Swimming Pool', 'CPA':'Car Parking', 'FS':' Feng Shui/Vaastu', 'SERVANT':'Servent',
                            'SECURITY':'Security', 'SC':'Shopping Center','GP':'Gas Pipeline', 'PARK':'Park', 'RWH':'Rain Water Harvesting', 'STP':'Sewage Treatment Plant',
                            'HK':'House Keeping', 'PB':'Power Backup', 'VP':'Visitor Parking'})

In [ ]:
house_train.columns

In [ ]:
ht = house_train['House Type'].unique()
ht

In [34]:
bt = house_train['Building Type'].unique()
bt

array(['AP', 'IH', 'IF', 'GC'], dtype=object)

In [ ]:
hf = house_train['House Facing'].unique()
hf

In [33]:
ws = house_train['Water Supply'].unique()
ws

array(['CORPORATION', 'CORP_BORE', 'BOREWELL'], dtype=object)

In [ ]:
lt = house_train['Lease Type'].unique()
lt

In [ ]:
f = house_train['Furnishing'].unique()
f

In [ ]:
p = house_train['Parking'].unique()
p

In [15]:
house_train.to_excel("HR_Train.xlsx",index=False)

## Test DataSet Pre-Processing

In [16]:
house_test = pd.read_excel('House_Rent_Test.xlsx')
house_test.head(2)

,id,type,locality,activation_date,latitude,longitude,lease_type,gym,lift,swimming_pool,...,property_age,bathroom,facing,cup_board,floor,total_floor,amenities,water_supply,building_type,balconies
0,ff8081815df539bc015df947ce976cca,BHK2,Basavanagudi,22-08-2017 09:00,12.941603,77.568156,FAMILY,0,1,0,...,1,2,N,2,3,3,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",CORP_BORE,AP,1
1,ff80818157288e9301572c05651853a6,BHK2,Rajaji Nagar,17-09-2017 16:33,12.998803,77.561887,ANYONE,0,0,0,...,7,1,S,2,0,3,"{""LIFT"":false,""GYM"":false,""INTERNET"":true,""AC""...",CORPORATION,IF,0

In [17]:
house_test.shape

(4500, 24)

In [18]:
house_test.isna().sum()

id                 0
type               0
locality           0
activation_date    0
latitude           0
longitude          0
lease_type         0
gym                0
lift               0
swimming_pool      0
negotiable         0
furnishing         0
parking            0
property_size      0
property_age       0
bathroom           0
facing             0
cup_board          0
floor              0
total_floor        0
amenities          0
water_supply       0
building_type      0
balconies          0
dtype: int64

In [19]:
import json

# Extract amenities information
amenities_test_list = house_test['amenities']

# Initialize a dictionary to store extracted values
amenities_test_dict = {}

# Iterate through each row
for am_t in amenities_test_list:
    amen_test_dict = json.loads(am_t)

    # Ensure that all keys are present in each row
    for key in amen_test_dict.keys():
        if key not in amenities_test_dict:
            amenities_test_dict[key] = []

    # Append values to the dictionary, filling with None if key is missing
    for key in amenities_test_dict.keys():
        amenities_test_dict[key].append(amen_test_dict.get(key, False))

# Add new columns for each amenity to the existing DataFrame
for key, values in amenities_test_dict.items():
    house_test[key] = values

# Display the modified DataFram
house_test

,id,type,locality,activation_date,latitude,longitude,lease_type,gym,lift,swimming_pool,...,SERVANT,SECURITY,SC,GP,PARK,RWH,STP,HK,PB,VP
0,ff8081815df539bc015df947ce976cca,BHK2,Basavanagudi,22-08-2017 09:00,12.941603,77.568156,FAMILY,0,1,0,...,False,True,False,False,False,False,False,False,True,False
1,ff80818157288e9301572c05651853a6,BHK2,Rajaji Nagar,17-09-2017 16:33,12.998803,77.561887,ANYONE,0,0,0,...,False,False,True,False,True,True,False,False,False,False
2,ff8081815f1afc58015f1b831fde166e,BHK1,Jeevan Bima Nagar,14-04-2018 17:27,12.966467,77.661063,ANYONE,0,0,0,...,False,False,True,False,True,True,False,False,True,False
3,ff8081816035b31901603f7922c046e0,BHK1,Jayanagar 1st Block,2017-11-12 13:15:00,12.941533,77.592606,ANYONE,0,0,0,...,False,False,True,False,False,False,False,False,False,False
4,ff8081815c3582f5015c38fc31aa73a4,BHK3,Whitefield Hope Farm Junction,2017-11-07 16:44:00,12.971083,77.751625,ANYONE,1,1,1,...,False,True,False,False,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,ff8081815216f51101521aa9d46c191f,BHK2,Hanumanthnagar,2018-10-06 18:22:00,12.941654,77.559999,FAMILY,0,0,0,...,False,True,True,False,False,False,False,False,False,False
4496,ff8081816098166901609bf52bb702a8,BHK2,Lakkasandra,21-01-2018 14:36,12.942973,77.597738,ANYONE,0,0,0,...,False,False,False,False,False,False,False,False,False,False
4497,ff808181629ac9860162a7ac1a4253bb,BHK1,"Jeevan Samskruthi Apartment, Shiridi Sai Templ...",30-05-2018 16:10,12.949315,77.713807,ANYONE,0,0,0,...,False,True,False,False,False,False,False,False,False,False
4498,ff8081815b57c717015b580af22f1bbd,BHK3,Mullur,2018-11-07 16:17:00,12.914104,77.716428,FAMILY,1,1,1,...,False,True,False,False,True,False,False,False,True,False
4499,ff808181615af5c101616150bd28356e,BHK3,Kaikondrahalli,27-03-2018 16:25,12.915296,77.676694,FAMILY,1,1,1,...,False,False,True,False,True,False,False,True,True,False

In [20]:
house_test.columns

Index(['id', 'type', 'locality', 'activation_date', 'latitude', 'longitude',
       'lease_type', 'gym', 'lift', 'swimming_pool', 'negotiable',
       'furnishing', 'parking', 'property_size', 'property_age', 'bathroom',
       'facing', 'cup_board', 'floor', 'total_floor', 'amenities',
       'water_supply', 'building_type', 'balconies', 'LIFT', 'GYM', 'INTERNET',
       'AC', 'CLUB', 'INTERCOM', 'POOL', 'CPA', 'FS', 'SERVANT', 'SECURITY',
       'SC', 'GP', 'PARK', 'RWH', 'STP', 'HK', 'PB', 'VP'],
      dtype='object')

In [21]:
remove_columns_test = ['gym', 'lift', 'swimming_pool','amenities']
house_test = house_test.drop(columns = remove_columns_test)

In [22]:
house_test['GYM'] = house_test['GYM'].astype(int)
house_test['LIFT'] = house_test['LIFT'].astype(int)
house_test['INTERNET'] = house_test['INTERNET'].astype(int)
house_test['AC'] = house_test['AC'].astype(int)
house_test['CLUB'] = house_test['CLUB'].astype(int)
house_test['INTERCOM'] = house_test['INTERCOM'].astype(int)
house_test['POOL'] = house_test['POOL'].astype(int)
house_test['CPA'] = house_test['CPA'].astype(int)
house_test['FS'] = house_test['FS'].astype(int)
house_test['SERVANT'] = house_test['SERVANT'].astype(int)
house_test['SECURITY'] = house_test['SECURITY'].astype(int)
house_test['SC'] = house_test['SC'].astype(int)
house_test['GP'] = house_test['GP'].astype(int)
house_test['PARK'] = house_test['PARK'].astype(int)
house_test['RWH'] = house_test['RWH'].astype(int)
house_test['STP'] = house_test['STP'].astype(int)
house_test['HK'] = house_test['HK'].astype(int)
house_test['PB'] = house_test['PB'].astype(int)
house_test['VP'] = house_test['VP'].astype(int)

house_test['bathroom'] = house_test['bathroom'].astype(int)
house_test['cup_board'] = house_test['cup_board'].astype(int)
house_test['floor'] = house_test['floor'].astype(int)
house_test['total_floor'] = house_test['total_floor'].astype(int)

house_test['property_size'] = house_test['property_size'].astype(int)
house_test['property_age'] = house_test['property_age'].astype(int)
house_test['balconies'] = house_test['balconies'].astype(int)
# house_test['rent'] = house_test['rent'].astype(int)
house_test['negotiable'] = house_test['negotiable'].astype(int)

In [23]:
house_test['latitude'] = house_test['latitude'].astype(float)
house_test['longitude'] = house_test['longitude'].astype(float)

house_test['locality'] = house_test['locality'].astype(str)
house_test['type'] = house_test['type'].astype(str)
house_test['id'] = house_test['id'].astype(str)
house_test['lease_type'] = house_test['lease_type'].astype(str)
house_test['furnishing'] = house_test['furnishing'].astype(str)
house_test['parking'] = house_test['parking'].astype(str)
house_test['facing'] = house_test['facing'].astype(str)
house_test['water_supply'] = house_test['water_supply'].astype(str)
house_test['building_type'] = house_test['building_type'].astype(str)

In [24]:
house_test = house_test.rename(columns={'id':'ID','type':'House Type','locality':'Locality','activation_date':'Activation Date','latitude':'Latitude','longitude':'Longitude',
                            'lease_type':'Lease Type','furnishing':'Furnishing','parking':'Parking','property_size':'Property Size','property_age':'Property Age',
                            'bathroom':'No of Bathroom','facing':'House Facing','cup_board':'No of Cup Board','floor':'Floor No Floor','water_supply':'Water Supply',
                            'building_type':'Building Type','balconies':'Balconies','negotiable':'Negotiable','LIFT':'Lift', 'GYM':'Gym', 'INTERNET':'Internet',
                            'AC':'Air Conditioning','CLUB':'Club', 'INTERCOM':'Intercom', 'POOL':'Swimming Pool', 'CPA':'Car Parking', 'FS':' Feng Shui/Vaastu', 'SERVANT':'Servent',
                            'SECURITY':'Security', 'SC':'Shopping Center','GP':'Gas Pipeline', 'PARK':'Park', 'RWH':'Rain Water Harvesting', 'STP':'Sewage Treatment Plant',
                            'HK':'House Keeping', 'PB':'Power Backup', 'VP':'Visitor Parking'})

In [25]:
house_test.columns

Index(['ID', 'House Type', 'Locality', 'Activation Date', 'Latitude',
       'Longitude', 'Lease Type', 'Negotiable', 'Furnishing', 'Parking',
       'Property Size', 'Property Age', 'No of Bathroom', 'House Facing',
       'No of Cup Board', 'Floor No Floor', 'total_floor', 'Water Supply',
       'Building Type', 'Balconies', 'Lift', 'Gym', 'Internet',
       'Air Conditioning', 'Club', 'Intercom', 'Swimming Pool', 'Car Parking',
       ' Feng Shui/Vaastu', 'Servent', 'Security', 'Shopping Center',
       'Gas Pipeline', 'Park', 'Rain Water Harvesting',
       'Sewage Treatment Plant', 'House Keeping', 'Power Backup',
       'Visitor Parking'],
      dtype='object')

In [26]:
house_test.to_excel("HR_Test.xlsx",index=False)